export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const TOGGLE_CART_HIDDEN = "TOGGLE_CART_HIDDEN";
export const ADD_ITEM = "ADD_ITEM";
export const CLEAR_ITEM_CART = "CLEAR_ITEM_CART";
export const REMOVE_ITEM = "REMOVE_ITEM";
